services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service-api
    command: uv run uvicorn app:combined_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      # Artık backend'in Redis'ine sesleniyor!
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped
    # networks kısmı yazmıyor çünkü otomatik olarak aşağıdaki 'default' ağına girecek

  nsfw-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run python -m src.workers.nsfw_worker # <-- DİKKAT: Dosya adının böyle olduğunu varsayıyorum
    environment:
      # AI servisi, backend'in Redis instance'ını (socialphoto_redis) kullanır
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped

  # 2. İşçi: Asıl Analist
  analyze-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run python -m src.workers.analyze_worker
    environment:
      # AI servisi, backend'in Redis instance'ını (socialphoto_redis) kullanır
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped
    # networks kısmı yazmıyor çünkü otomatik olarak aşağıdaki 'default' ağına girecek

networks:
  default:
    name: socialphoto-backend_default # Backend klasörünün ismine göre değişir
    external: true