services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service-api
    command: uv run uvicorn app:combined_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # .env dosyasındaki REDIS_HOST (genelde localhost) değerini ezer.
      # Local geliştirme için .env kullanılırken, Docker ağında container'ların birbirini bulabilmesi için bu override zorunludur.
      # Artık backend'in Redis'ine (socialphoto_redis) sesleniyor!
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped
    # networks kısmı yazmıyor çünkü otomatik olarak aşağıdaki 'default' ağına girecek

  nsfw-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run python -m src.workers.nsfw_worker # <-- DİKKAT: Dosya adının böyle olduğunu varsayıyorum
    env_file:
      - .env
    environment:
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped

  analyze-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run python -m src.workers.analyze_worker
    env_file:
      - .env
    environment:
      - REDIS_HOST=socialphoto_redis
    volumes:
      - .:/app
    restart: unless-stopped
    # networks kısmı yazmıyor çünkü otomatik olarak aşağıdaki 'default' ağına girecek

networks:
  default:
    name: socialphoto_backend_default # Backend klasörünün ismine göre değişir
    external: true
